using System.Text.Json;
using System.Text.Json.Serialization;

namespace tryAGI.OpenAI.OpenAISharp;

/// <inheritdoc />
[JsonSourceGenerationOptions(
    JsonSerializerDefaults.Web,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(OpenAIRealtimeClientEvent))]
[JsonSerializable(typeof(OpenAIRealtimeSessionUpdateEvent))]
[JsonSerializable(typeof(OpenAIRealtimeResponseCreateEvent))]
[JsonSerializable(typeof(OpenAIRealtimeResponseCancelEvent))]
[JsonSerializable(typeof(OpenAIRealtimeConversationItemCreateEvent))]
[JsonSerializable(typeof(OpenAIRealtimeConversationItemDeleteEvent))]
[JsonSerializable(typeof(OpenAIRealtimeConversationItemTruncateEvent))]
[JsonSerializable(typeof(OpenAIRealtimeInputAudioBufferAppendEvent))]
[JsonSerializable(typeof(OpenAIRealtimeInputAudioBufferCommitEvent))]
[JsonSerializable(typeof(OpenAIRealtimeInputAudioBufferClearEvent))]
[JsonSerializable(typeof(OpenAIRealtimeOutputAudioBufferClearEvent))]
[JsonSerializable(typeof(OpenAIRealtimeSessionInputAudioBufferAppendEvent))]
[JsonSerializable(typeof(OpenAIRealtimeSessionUpdate))]
[JsonSerializable(typeof(OpenAIRealtimeAudioConfig))]
[JsonSerializable(typeof(OpenAIRealtimeTranscriptionAudioConfig))]
[JsonSerializable(typeof(OpenAIRealtimeInputAudioConfig))]
[JsonSerializable(typeof(OpenAIRealtimeOutputAudioConfig))]
[JsonSerializable(typeof(OpenAIRealtimeAudioFormat))]
[JsonSerializable(typeof(OpenAIRealtimeInputAudioTranscription))]
[JsonSerializable(typeof(OpenAIRealtimeTurnDetection))]
[JsonSerializable(typeof(OpenAIRealtimeTranscriptionSessionUpdate))]
[JsonSerializable(typeof(OpenAIRealtimeNoiseReduction))]
[JsonSerializable(typeof(OpenAIRealtimeResponse))]
[JsonSerializable(typeof(OpenAIRealtimePrompt))]
[JsonSerializable(typeof(OpenAIRealtimeReasoning))]
[JsonSerializable(typeof(OpenAIRealtimeTracingConfig))]
[JsonSerializable(typeof(OpenAIRealtimeTruncation))]
[JsonSerializable(typeof(OpenAIRealtimeToolChoice))]
[JsonSerializable(typeof(OpenAIRealtimeConversationItem))]
[JsonSerializable(typeof(OpenAIRealtimeConversationItem[]))]
[JsonSerializable(typeof(OpenAIRealtimeContent))]
[JsonSerializable(typeof(OpenAIRealtimeContent[]))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(OpenAIRealtimeInputTextContent))]
[JsonSerializable(typeof(OpenAIRealtimeInputImageContent))]
[JsonSerializable(typeof(OpenAIRealtimeInputAudioContent))]
[JsonSerializable(typeof(OpenAIRealtimeImageUrl))]
[JsonSerializable(typeof(OpenAIRealtimeEvent))]
[JsonSerializable(typeof(OpenAIRealtimeErrorEvent))]
[JsonSerializable(typeof(OpenAIRealtimeSessionEvent))]
[JsonSerializable(typeof(OpenAIRealtimeResponseEvent))]
[JsonSerializable(typeof(OpenAIRealtimeConversationItemEvent))]
[JsonSerializable(typeof(OpenAIRealtimeConversationEvent))]
[JsonSerializable(typeof(OpenAIRealtimeContentPartEvent))]
[JsonSerializable(typeof(OpenAIRealtimeRateLimitsEvent))]
[JsonSerializable(typeof(OpenAIRealtimeUnknownEvent))]
[JsonSerializable(typeof(OpenAIRealtimeAudioDeltaEvent))]
[JsonSerializable(typeof(OpenAIRealtimeTextDeltaEvent))]
[JsonSerializable(typeof(OpenAIRealtimeFunctionCallArgsDeltaEvent))]
[JsonSerializable(typeof(OpenAIRealtimeFunctionCallArgsDoneEvent))]
[JsonSerializable(typeof(OpenAIRealtimeOutputItemDoneEvent))]
[JsonSerializable(typeof(OpenAIRealtimeSpeechStartedEvent))]
[JsonSerializable(typeof(OpenAIRealtimeSpeechStoppedEvent))]
[JsonSerializable(typeof(OpenAIRealtimeTranscriptionCompletedEvent))]
[JsonSerializable(typeof(OpenAIRealtimeTranscriptionDeltaEvent))]
[JsonSerializable(typeof(OpenAIRealtimeError))]
[JsonSerializable(typeof(OpenAIRealtimeTool))]
[JsonSerializable(typeof(OpenAIRealtimeTool[]))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
public partial class JsonContext : JsonSerializerContext;
