#nullable enable

using System.CommandLine;

namespace tryAGI.OpenAI.Cli.GeneratedApi.Commands;

internal static partial class CompletionsCreateCompletionCommandApiCommand
{
    private static Option<global::tryAGI.OpenAI.AnyOf<string, global::tryAGI.OpenAI.CreateCompletionRequestModel?>> Model { get; } = new(
        name: @"--model")
    {
        Description = @"ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models) for descriptions of them.
",
        Required = true,
    };

    private static Option<global::tryAGI.OpenAI.OneOf<string, global::System.Collections.Generic.IList<string>, global::System.Collections.Generic.IList<int>, global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<int>>>?> Prompt { get; } = new(
        name: @"--prompt")
    {
        Description = @"The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays.

Note that <|endoftext|> is the document separator that the model sees during training, so if a prompt is not specified the model will generate as if from the beginning of a new document.
",
    };

    private static Option<int?> BestOf { get; } = new(
        name: @"--best-of")
    {
        Description = @"Generates `best_of` completions server-side and returns the ""best"" (the one with the highest log probability per token). Results cannot be streamed.

When used with `n`, `best_of` controls the number of candidate completions and `n` specifies how many to return – `best_of` must be greater than `n`.

**Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`.
",
    };

    private static Option<bool?> Echo { get; } = CliRuntime.CreateNullableBoolOption(
        name: @"--echo",
        description: @"Echo back the prompt in addition to the completion
");

    private static Option<double?> FrequencyPenalty { get; } = new(
        name: @"--frequency-penalty")
    {
        Description = @"Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.

[See more information about frequency and presence penalties.](/docs/guides/text-generation)
",
    };

    private static Option<global::System.Collections.Generic.Dictionary<string, int>?> LogitBias { get; } = new(
        name: @"--logit-bias")
    {
        Description = @"Modify the likelihood of specified tokens appearing in the completion.

Accepts a JSON object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.

As an example, you can pass `{""50256"": -100}` to prevent the <|endoftext|> token from being generated.
",
    };

    private static Option<int?> Logprobs { get; } = new(
        name: @"--logprobs")
    {
        Description = @"Include the log probabilities on the `logprobs` most likely output tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.

The maximum value for `logprobs` is 5.
",
    };

    private static Option<int?> MaxTokens { get; } = new(
        name: @"--max-tokens")
    {
        Description = @"The maximum number of [tokens](/tokenizer) that can be generated in the completion.

The token count of your prompt plus `max_tokens` cannot exceed the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens.
",
    };

    private static Option<int?> N { get; } = new(
        name: @"--n")
    {
        Description = @"How many completions to generate for each prompt.

**Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`.
",
    };

    private static Option<double?> PresencePenalty { get; } = new(
        name: @"--presence-penalty")
    {
        Description = @"Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.

[See more information about frequency and presence penalties.](/docs/guides/text-generation)
",
    };

    private static Option<long?> Seed { get; } = new(
        name: @"--seed")
    {
        Description = @"If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.

Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.
",
    };

    private static Option<global::tryAGI.OpenAI.StopConfiguration?> Stop { get; } = new(
        name: @"--stop")
    {
        Description = @"Not supported with latest reasoning models `o3` and `o4-mini`.

Up to 4 sequences where the API will stop generating further tokens. The
returned text will not contain the stop sequence.
",
    };

    private static Option<bool?> Stream { get; } = CliRuntime.CreateNullableBoolOption(
        name: @"--stream",
        description: @"Whether to stream back partial progress. If set, tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions).
");

    private static Option<global::tryAGI.OpenAI.ChatCompletionStreamOptionsVariant1?> StreamOptions { get; } = new(
        name: @"--stream-options")
    {
        Description = @"",
    };

    private static Option<string?> Suffix { get; } = new(
        name: @"--suffix")
    {
        Description = @"The suffix that comes after a completion of inserted text.

This parameter is only supported for `gpt-3.5-turbo-instruct`.
",
    };

    private static Option<double?> Temperature { get; } = new(
        name: @"--temperature")
    {
        Description = @"What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

We generally recommend altering this or `top_p` but not both.
",
    };

    private static Option<double?> TopP { get; } = new(
        name: @"--top-p")
    {
        Description = @"An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.

We generally recommend altering this or `temperature` but not both.
",
    };

    private static Option<string?> User { get; } = new(
        name: @"--user")
    {
        Description = @"A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).
",
    };
      private static Option<string?> Input { get; } = new("--input")
      {
          Description = "Load request JSON from a file path, '-' for stdin, or an inline JSON object/array string.",
      };

      private static Option<string?> RequestJson { get; } = new("--request-json")
      {
          Description = "Request body as JSON.",
          Hidden = true,
      };

      private static Option<string?> RequestFile { get; } = new("--request-file")
      {
          Description = "Path to a JSON request file, or '-' for stdin.",
          Hidden = true,
      };

                    private static string FormatResponse(ParseResult parseResult, global::tryAGI.OpenAI.CreateCompletionResponse value, global::System.Text.Json.Serialization.JsonSerializerContext context, bool truncateLongStrings)
                    {
                        string? text = null;
                        CustomizeResponseText(parseResult, value, ref text);
                        if (!string.IsNullOrWhiteSpace(text))
                        {
                            return text;
                        }

                        var hints = new Dictionary<string, CliFormatHint>(StringComparer.OrdinalIgnoreCase)
                        {
                        };
                        CustomizeResponseFormatHints(hints);
                        return CliRuntime.FormatHumanReadable(value, context, truncateLongStrings, hints);
                    }

                    static partial void CustomizeResponseText(ParseResult parseResult, global::tryAGI.OpenAI.CreateCompletionResponse value, ref string? text);
                    static partial void CustomizeResponseFormatHints(Dictionary<string, CliFormatHint> hints);


    public static Command Create()
    {
        var command = new Command(@"create-completion", @"Creates a completion for the provided prompt and parameters.

Returns a completion object, or a sequence of completion objects if the request is streamed.
");
                        command.Options.Add(Model);
                        command.Options.Add(Prompt);
                        command.Options.Add(BestOf);
                        command.Options.Add(Echo);
                        command.Options.Add(FrequencyPenalty);
                        command.Options.Add(LogitBias);
                        command.Options.Add(Logprobs);
                        command.Options.Add(MaxTokens);
                        command.Options.Add(N);
                        command.Options.Add(PresencePenalty);
                        command.Options.Add(Seed);
                        command.Options.Add(Stop);
                        command.Options.Add(Stream);
                        command.Options.Add(StreamOptions);
                        command.Options.Add(Suffix);
                        command.Options.Add(Temperature);
                        command.Options.Add(TopP);
                        command.Options.Add(User);
          command.Options.Add(Input);
          command.Options.Add(RequestJson);
          command.Options.Add(RequestFile);
          command.Validators.Add(result =>
          {
              var hasInput = result.GetResult(Input) is not null;
              var hasRequestJson = result.GetResult(RequestJson) is not null;
              var hasRequestFile = result.GetResult(RequestFile) is not null;
              var specifiedCount = (hasInput ? 1 : 0) + (hasRequestJson ? 1 : 0) + (hasRequestFile ? 1 : 0);
              if (specifiedCount > 1)
              {
                  result.AddError("Specify at most one of --input, --request-json, or --request-file.");
              }
          });

        command.SetAction(async (ParseResult parseResult, CancellationToken cancellationToken) =>
            await CliRuntime.RunAsync(async () =>
            {
                        var __requestBase = await CliRuntime.ReadRequestOrDefaultAsync<global::tryAGI.OpenAI.CreateCompletionRequest>(
                            parseResult,
                            Input,
                            RequestJson,
                            RequestFile,
                            global::tryAGI.OpenAI.SourceGenerationContext.Default,
                            cancellationToken).ConfigureAwait(false);
                        var model = parseResult.GetRequiredValue(Model);
                        var prompt = parseResult.GetValue(Prompt) ?? __requestBase?.Prompt;
                        var bestOf = parseResult.GetValue(BestOf) ?? __requestBase?.BestOf;
                        var echo = parseResult.GetValue(Echo) ?? __requestBase?.Echo;
                        var frequencyPenalty = parseResult.GetValue(FrequencyPenalty) ?? __requestBase?.FrequencyPenalty;
                        var logitBias = parseResult.GetValue(LogitBias) ?? __requestBase?.LogitBias;
                        var logprobs = parseResult.GetValue(Logprobs) ?? __requestBase?.Logprobs;
                        var maxTokens = parseResult.GetValue(MaxTokens) ?? __requestBase?.MaxTokens;
                        var n = parseResult.GetValue(N) ?? __requestBase?.N;
                        var presencePenalty = parseResult.GetValue(PresencePenalty) ?? __requestBase?.PresencePenalty;
                        var seed = parseResult.GetValue(Seed) ?? __requestBase?.Seed;
                        var stop = parseResult.GetValue(Stop) ?? __requestBase?.Stop;
                        var stream = parseResult.GetValue(Stream) ?? __requestBase?.Stream;
                        var streamOptions = parseResult.GetValue(StreamOptions) ?? __requestBase?.StreamOptions;
                        var suffix = parseResult.GetValue(Suffix) ?? __requestBase?.Suffix;
                        var temperature = parseResult.GetValue(Temperature) ?? __requestBase?.Temperature;
                        var topP = parseResult.GetValue(TopP) ?? __requestBase?.TopP;
                        var user = parseResult.GetValue(User) ?? __requestBase?.User;
                using var client = await CliRuntime.CreateClientAsync(parseResult, cancellationToken).ConfigureAwait(false);


                                var response = await client.Completions.CreateCompletionAsync(
                                    model: model,
                                    prompt: prompt,
                                    bestOf: bestOf,
                                    echo: echo,
                                    frequencyPenalty: frequencyPenalty,
                                    logitBias: logitBias,
                                    logprobs: logprobs,
                                    maxTokens: maxTokens,
                                    n: n,
                                    presencePenalty: presencePenalty,
                                    seed: seed,
                                    stop: stop,
                                    stream: stream,
                                    streamOptions: streamOptions,
                                    suffix: suffix,
                                    temperature: temperature,
                                    topP: topP,
                                    user: user,
                                    cancellationToken: cancellationToken).ConfigureAwait(false);


                                if (!await CliRuntime.TryWriteOutputDirectoryAsync(
                                        parseResult,
                                        response,
                                        global::tryAGI.OpenAI.SourceGenerationContext.Default,
                                        @"Choices",
                                        cancellationToken).ConfigureAwait(false))
                                {
                                await CliRuntime.WriteResponseAsync(
                                    parseResult,
                                    response,
                                    global::tryAGI.OpenAI.SourceGenerationContext.Default,
                                    FormatResponse,
                                    cancellationToken).ConfigureAwait(false);
                                }
            }, cancellationToken).ConfigureAwait(false));
        return command;
    }
}