#nullable enable

using System.CommandLine;

namespace tryAGI.OpenAI.Cli.GeneratedApi.Commands;

internal sealed record CreateImageRequestOptionSet(
    Option<string> Prompt,
                     Option<int?> N,
                     Option<global::tryAGI.OpenAI.CreateImageRequestQuality?> Quality,
                     Option<global::tryAGI.OpenAI.CreateImageRequestResponseFormat?> ResponseFormat,
                     Option<global::tryAGI.OpenAI.CreateImageRequestOutputFormat?> OutputFormat,
                     Option<int?> OutputCompression,
                     Option<bool?> Stream,
                     Option<int?> PartialImages,
                     Option<global::tryAGI.OpenAI.CreateImageRequestModeration?> Moderation,
                     Option<global::tryAGI.OpenAI.CreateImageRequestBackground?> Background,
                     Option<global::tryAGI.OpenAI.CreateImageRequestStyle?> Style,
                     Option<string?> User)
{
    public static CreateImageRequestOptionSet Create(string? prefix = null)
    {
        var normalizedPrefix = string.IsNullOrWhiteSpace(prefix)
            ? string.Empty
            : prefix.Trim().Trim('-') + "-";
        return new CreateImageRequestOptionSet(
                        Prompt: new Option<string>($"--{normalizedPrefix}prompt")
                {
                    Description = @"A text description of the desired image(s). The maximum length is 32000 characters for the GPT image models, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.",
                    Required = true,
                },
                N: new Option<int?>($"--{normalizedPrefix}n")
                {
                    Description = @"The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.",
                },
                Quality: new Option<global::tryAGI.OpenAI.CreateImageRequestQuality?>($"--{normalizedPrefix}quality")
                {
                    Description = @"The quality of the image that will be generated.

- `auto` (default value) will automatically select the best quality for the given model.
- `high`, `medium` and `low` are supported for the GPT image models.
- `hd` and `standard` are supported for `dall-e-3`.
- `standard` is the only option for `dall-e-2`.
",
                },
                ResponseFormat: new Option<global::tryAGI.OpenAI.CreateImageRequestResponseFormat?>($"--{normalizedPrefix}response-format")
                {
                    Description = @"The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for the GPT image models, which always return base64-encoded images.",
                },
                OutputFormat: new Option<global::tryAGI.OpenAI.CreateImageRequestOutputFormat?>($"--{normalizedPrefix}output-format")
                {
                    Description = @"The format in which the generated images are returned. This parameter is only supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.",
                },
                OutputCompression: new Option<int?>($"--{normalizedPrefix}output-compression")
                {
                    Description = @"The compression level (0-100%) for the generated images. This parameter is only supported for the GPT image models with the `webp` or `jpeg` output formats, and defaults to 100.",
                },
                Stream: CliRuntime.CreateNullableBoolOption(name: $"--{normalizedPrefix}stream", description: @"Generate the image in streaming mode. Defaults to `false`. See the
[Image generation guide](/docs/guides/image-generation) for more information.
This parameter is only supported for the GPT image models.
"),
                PartialImages: new Option<int?>($"--{normalizedPrefix}partial-images")
                {
                    Description = @"",
                },
                Moderation: new Option<global::tryAGI.OpenAI.CreateImageRequestModeration?>($"--{normalizedPrefix}moderation")
                {
                    Description = @"Control the content-moderation level for images generated by the GPT image models. Must be either `low` for less restrictive filtering or `auto` (default value).",
                },
                Background: new Option<global::tryAGI.OpenAI.CreateImageRequestBackground?>($"--{normalizedPrefix}background")
                {
                    Description = @"Allows to set transparency for the background of the generated image(s).
This parameter is only supported for the GPT image models. Must be one of
`transparent`, `opaque` or `auto` (default value). When `auto` is used, the
model will automatically determine the best background for the image.

If `transparent`, the output format needs to support transparency, so it
should be set to either `png` (default value) or `webp`.
",
                },
                Style: new Option<global::tryAGI.OpenAI.CreateImageRequestStyle?>($"--{normalizedPrefix}style")
                {
                    Description = @"The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.",
                },
                User: new Option<string?>($"--{normalizedPrefix}user")
                {
                    Description = @"A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).
",
                }
        );
    }
}