#nullable enable
#pragma warning disable CS0618

using System.CommandLine;

namespace tryAGI.OpenAI.Cli.GeneratedApi.Commands;

internal static partial class RealtimeCreateCallCommandApiCommand
{
    private static Option<string> Sdp { get; } = new(
        name: @"--sdp")
    {
        Description = @"WebRTC Session Description Protocol (SDP) offer generated by the caller.",
        Required = true,
    };
    private static readonly RealtimeSessionCreateRequestGAOptionSet SessionOptions = RealtimeSessionCreateRequestGAOptionSet.Create(@"session");
      private static Option<string?> Input { get; } = new(@"--input")
      {
          Description = "Load request JSON from a file path, '-' for stdin, or an inline JSON object/array string.",
      };

      private static Option<string?> RequestJson { get; } = new(@"--request-json")
      {
          Description = "Request body as JSON.",
          Hidden = true,
      };

      private static Option<string?> RequestFile { get; } = new(@"--request-file")
      {
          Description = "Path to a JSON request file, or '-' for stdin.",
          Hidden = true,
      };

                    private static string FormatResponse(ParseResult parseResult, string value, global::System.Text.Json.Serialization.JsonSerializerContext context, bool truncateLongStrings)
                    {
                        string? text = null;
                        CustomizeResponseText(parseResult, value, ref text);
                        if (!string.IsNullOrWhiteSpace(text))
                        {
                            return text;
                        }

                        var hints = new Dictionary<string, CliFormatHint>(StringComparer.OrdinalIgnoreCase)
                        {
                        };
                        CustomizeResponseFormatHints(hints);
                        return CliRuntime.FormatHumanReadable(value, context, truncateLongStrings, hints);
                    }

                    static partial void CustomizeResponseText(ParseResult parseResult, string value, ref string? text);
                    static partial void CustomizeResponseFormatHints(Dictionary<string, CliFormatHint> hints);


    public static Command Create()
    {
        var command = new Command(@"create-call", @"Create a new Realtime API call over WebRTC and receive the SDP answer needed
to complete the peer connection.");
                        command.Options.Add(Sdp);                        command.Options.Add(SessionOptions.Type);
                        command.Options.Add(SessionOptions.OutputModalities);
                        command.Options.Add(SessionOptions.Instructions);
                        command.Options.Add(SessionOptions.Include);
                        command.Options.Add(SessionOptions.ParallelToolCalls);
          command.Options.Add(Input);
          command.Options.Add(RequestJson);
          command.Options.Add(RequestFile);
          command.Validators.Add(result =>
          {
              var hasInput = result.GetResult(Input) is not null;
              var hasRequestJson = result.GetResult(RequestJson) is not null;
              var hasRequestFile = result.GetResult(RequestFile) is not null;
              var specifiedCount = (hasInput ? 1 : 0) + (hasRequestJson ? 1 : 0) + (hasRequestFile ? 1 : 0);
              if (specifiedCount > 1)
              {
                  result.AddError(@"Specify at most one of --input, --request-json, or --request-file.");
              }
          });

        command.SetAction(async (ParseResult parseResult, CancellationToken cancellationToken) =>
            await CliRuntime.RunAsync(async () =>
            {
                        var __requestBase = await CliRuntime.ReadRequestOrDefaultAsync<global::tryAGI.OpenAI.RealtimeCallCreateRequest>(
                            parseResult,
                            Input,
                            RequestJson,
                            RequestFile,
                            global::tryAGI.OpenAI.SourceGenerationContext.Default,
                            cancellationToken).ConfigureAwait(false);
                        var sdp = parseResult.GetRequiredValue(Sdp);

                        var __sessionBase = __requestBase?.Session;                        var sessionType = CliRuntime.WasSpecified(parseResult, SessionOptions.Type) ? parseResult.GetValue(SessionOptions.Type) : __sessionBase is not null ? __sessionBase.Type : default;
                        var sessionOutputModalities = CliRuntime.WasSpecified(parseResult, SessionOptions.OutputModalities) ? parseResult.GetValue(SessionOptions.OutputModalities) : __sessionBase is not null ? __sessionBase.OutputModalities : default;
                        var sessionInstructions = CliRuntime.WasSpecified(parseResult, SessionOptions.Instructions) ? parseResult.GetValue(SessionOptions.Instructions) : __sessionBase is not null ? __sessionBase.Instructions : default;
                        var sessionInclude = CliRuntime.WasSpecified(parseResult, SessionOptions.Include) ? parseResult.GetValue(SessionOptions.Include) : __sessionBase is not null ? __sessionBase.Include : default;
                        var sessionParallelToolCalls = CliRuntime.WasSpecified(parseResult, SessionOptions.ParallelToolCalls) ? parseResult.GetValue(SessionOptions.ParallelToolCalls) : __sessionBase is not null ? __sessionBase.ParallelToolCalls : default;
                        var __sessionSpecified = CliRuntime.WasSpecified(parseResult, SessionOptions.Type) || CliRuntime.WasSpecified(parseResult, SessionOptions.OutputModalities) || CliRuntime.WasSpecified(parseResult, SessionOptions.Instructions) || CliRuntime.WasSpecified(parseResult, SessionOptions.Include) || CliRuntime.WasSpecified(parseResult, SessionOptions.ParallelToolCalls);
                        var session =
                            __sessionSpecified || __sessionBase is not null
                                ? new global::tryAGI.OpenAI.RealtimeSessionCreateRequestGA
                                {
                                Type = sessionType,
                                OutputModalities = sessionOutputModalities,
                                Instructions = sessionInstructions,
                                Include = sessionInclude,
                                ParallelToolCalls = sessionParallelToolCalls,
                                }
                                : __sessionBase;
                using var client = await CliRuntime.CreateClientAsync(parseResult, cancellationToken).ConfigureAwait(false);


                                var response = await client.Realtime.CreateCallAsync(
                                    sdp: sdp,
                                    session: session,
                                    cancellationToken: cancellationToken).ConfigureAwait(false);


                                await CliRuntime.WriteResponseAsync(
                                    parseResult,
                                    response,
                                    global::tryAGI.OpenAI.SourceGenerationContext.Default,
                                    FormatResponse,
                                    cancellationToken).ConfigureAwait(false);
            }, cancellationToken).ConfigureAwait(false));
        return command;
    }
}