name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    if: github.event.pull_request.draft == false
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      generate-build-number: false
      conventional-commits-publish-conditions: false
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'